# -*- coding: utf-8 -*-
"""aap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iayOkqFq2nDihUI4IZdWlDS_zjroexyE
"""

from flask import Flask, render_template, request
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

app = Flask(__name__)

calidad = ctrl.Antecedent(np.arange(0, 10.1, 0.1), 'calidad')
stock = ctrl.Antecedent(np.arange(1, 100.1, 1), 'stock')
descuento = ctrl.Consequent(np.arange(0, 25.1, 0.1), 'descuento')

calidad['baja']    = fuzz.trapmf(calidad.universe, [0, 0, 2, 4])
calidad['media']   = fuzz.trapmf(calidad.universe, [3, 5, 6, 8])
calidad['alta']    = fuzz.trapmf(calidad.universe, [7, 9, 10, 10])

stock['bajo']  = fuzz.trapmf(stock.universe, [1, 1, 20, 40])
stock['medio'] = fuzz.trapmf(stock.universe, [30, 50, 60, 80])
stock['alto']  = fuzz.trapmf(stock.universe, [70, 90, 100, 100])

descuento['bajo']     = fuzz.trapmf(descuento.universe, [0, 0, 2, 5])
descuento['moderado'] = fuzz.trapmf(descuento.universe, [4, 7, 10, 13])
descuento['alto']     = fuzz.trapmf(descuento.universe, [12, 16, 20, 25])

rules = [
    ctrl.Rule(calidad['baja']  & stock['alto'],  descuento['alto']),
    ctrl.Rule(calidad['media'] & stock['medio'], descuento['moderado']),
    ctrl.Rule(calidad['alta']  & stock['bajo'],  descuento['bajo']),
    ctrl.Rule(calidad['baja']  & stock['medio'], descuento['moderado']),
    ctrl.Rule(calidad['media'] & stock['bajo'],  descuento['bajo']),
    ctrl.Rule(calidad['alta']  & stock['medio'], descuento['moderado']),
    ctrl.Rule(calidad['media'] & stock['alto'],  descuento['alto']),
    ctrl.Rule(calidad['baja']  & stock['bajo'],  descuento['bajo']),
    ctrl.Rule(calidad['alta']  & stock['alto'],  descuento['moderado'])
]

discount_ctrl = ctrl.ControlSystem(rules)
discount_system = ctrl.ControlSystemSimulation(discount_ctrl)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/calcular', methods=['POST'])
def calcular():
    calidad_val = float(request.form['calidad'])
    stock_val = float(request.form['stock'])
    precio_val = float(request.form['precio'])

    discount_system.input['calidad'] = calidad_val
    discount_system.input['stock'] = stock_val
    discount_system.compute()
    porcentaje = float(discount_system.output['descuento'])
    porcentaje = max(0, min(25, porcentaje))

    monto_desc = precio_val * porcentaje / 100.0
    precio_final = precio_val - monto_desc

    return f"""
    <h3>Descuento sugerido: {porcentaje:.2f}%</h3>
    <p>Monto de descuento: S/ {monto_desc:.2f}</p>
    <p>Precio final: S/ {precio_final:.2f}</p>
    <a href="/">Volver</a>
    """

if __name__ == '__main__':
    app.run(debug=True)
